### ISSUE TITLE
Tiny Yolo failed to compiled with Movidius

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [martinbel/yolo2NCS#1]
I tried implementing for Tiny Yolo and training and freezing was done successfully. However, when compiling with Movidius NCDK 2.08 and 2.10 it raised error [Error 5] Toolkit Error: Stage Details Not Supported: LeakyRelu.

Do you know the reason of this behavior? Any lead to this will be appreciated.
Thanks.

**Comment by martinbel** [comment]
Not really... Have you made changes to the code? 
Are you using the same keras/tf versions I used?

**Comment by Ajaz-Ahmad** [comment]
Hi,

I used tf version 1.9.0 and Keras gpu version 2.1.5 as stated in your document. I am using Tiny Yolo backend. During training the loss is decreased as expected and the weights are generated.
I use my config file and changed DarknetReferenceNet init method as per Tiny Yolo architecture to load weights. The weights were loaded successfully and graph was generated. 
I am using Virtual Machine for NCSDK installation, I tried first with 2.08.01.02.
I am attaching all the files I made changes to and the generated graph file. 

[Zipfiles.zip](https://github.com/martinbel/yolo2NCS/files/3461306/Zipfiles.zip)

I tried again with the new generated graph as per above files in Zip but this time I got the following error during freezing of the graph:
ValueError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: norm_1/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, Truncate=false](norm_1/Prod). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.)

Can you help me with it?
Thanks for your response.

**Comment by martinbel** [comment]
I haven't used this code for Tiny Yolo. I've used a smaller network based on the Darknet Reference model, see darknet site. 
https://github.com/martinbel/yolo2NCS/blob/master/ncs_darknetreference/DarknetReferenceNet.py
You probably need to make changes for Tiny Yolo but you can reproduce what I did first. 

I've installed the NCSDK via docker so it's all in one machine. I foudn this was the simplest approach to experiment.

**Comment by Ajaz-Ahmad** [comment]
Hi,
I am using your code partially and implemented pure tensorflow Tiny Yolo. I have checked the data preparation method and center calculations, box co-ordinates for resized images are same for my program as well. However, it differs in feature extraction network which I have given below:
    def build_networks(self, inputs):
        net = self.conv_layer(inputs, [3, 3, 3, 32], name = '0_conv')
        net = self.pooling_layer(net, name = '1_pool')

        net = self.conv_layer(net, [3, 3, 32, 64], name = '2_conv')
        net = self.pooling_layer(net, name = '3_pool')

        net = self.conv_layer(net, [3, 3, 64, 128], name = '4_conv')
        net = self.conv_layer(net, [1, 1, 128, 64], name = '5_conv')
        net = self.conv_layer(net, [3, 3, 64, 128], name = '6_conv')
        net = self.pooling_layer(net, name = '7_pool')

        net = self.conv_layer(net, [3, 3, 128, 256], name = '8_conv')
        net = self.conv_layer(net, [1, 1, 256, 128], name = '9_conv')
        net = self.conv_layer(net, [3, 3, 128, 256], name = '10_conv')
        net = self.pooling_layer(net, name = '11_pool')

        net = self.conv_layer(net, [3, 3, 256, 512], name = '12_conv')
        net = self.conv_layer(net, [1, 1, 512, 256], name = '13_conv')
        net = self.conv_layer(net, [3, 3, 256, 512], name = '14_conv')
        net = self.conv_layer(net, [1, 1, 512, 256], name = '15_conv')
        net16 = self.conv_layer(net, [3, 3, 256, 512], name = '16_conv')
        net = self.pooling_layer(net16, name = '17_pool')

        net = self.conv_layer(net, [3, 3, 512, 1024], name = '18_conv')
        net = self.conv_layer(net, [1, 1, 1024, 512], name = '19_conv')
        net = self.conv_layer(net, [3, 3, 512, 1024], name = '20_conv')
        net = self.conv_layer(net, [1, 1, 1024, 512], name = '21_conv')
        net = self.conv_layer(net, [3, 3, 512, 1024], name = '22_conv')

        net = self.conv_layer(net, [3, 3, 1024, 1024], name = '23_conv')
        net24 = self.conv_layer(net, [3, 3, 1024, 1024], name = '24_conv')

        net = self.conv_layer(net16, [1, 1, 512, 64], name = '26_conv')
        net = self.reorg(net)

        net = tf.concat([net, net24], 3)

        net = self.conv_layer(net, [3, 3, int(net.get_shape()[3]), 1024], name = '29_conv')
        net = self.conv_layer(net, [1, 1, 1024, self.box_per_cell * (self.num_class + 5)], batch_norm=False, name = '30_conv')

        return net

The loss layer is inspired by your method of calculations but it seems I have made some mistake that the calculations come as NAN.  Below is my loss layer function and max_box_per_image is 10.
Can you help me here?
Another questions is where do you normalize to bbox co-ordinates, if you do that?
If you need more info please let me know I will add files to my repository.
Your help is appreciated. 
Thanks.

def loss_layer(self,y_true,y_pred):#, y_true=shape=(1, 1, 1, max_box_per_image , 4)
        #13,13,5,8....................1,1,1,10,4-ytrue
        #?,13,13,5,8
        #4,
        print('ytrue',y_true)
        y_pred=tf.reshape(y_pred,[self.batch_size,self.cell_size,self.cell_size,self.box_per_cell,5+self.num_class])
        print('ypred',y_pred)
        mask_shape = tf.shape(y_true)[:4]
        print(mask_shape)
        #1,13,13,1,1
        cell_x = tf.to_float(tf.reshape(tf.tile(tf.range(self.cell_size), [self.cell_size]), (1, self.cell_size, self.cell_size, 1, 1)))
        print(cell_x)
        #1,13,13,1,1
        cell_y = tf.to_float(tf.reshape(tf.tile(tf.range(self.cell_size), [self.cell_size]), (1, self.cell_size, self.cell_size, 1, 1)))
        print(cell_y)
        cell_y = tf.transpose(cell_y, (0,2,1,3,4))
        print(cell_y)
        #1,13,13,5,2
        cell_grid = tf.tile(tf.concat([cell_x,cell_y], -1), [self.batch_size, 1, 1, self.box_per_cell, 1])
        print(cell_grid)
        #?,13,13,5
        coord_mask = tf.zeros(mask_shape)
        #?,13,13,5
        class_mask = tf.zeros(mask_shape)

        seen = tf.Variable(0.)
        total_recall = tf.Variable(0.)

        """
        Adjust prediction
        """
        ### adjust x and y
        print('y_pred[...,:2]',y_pred[...,:2])
        print('cell_grid',cell_grid)
        pred_box_xy = tf.sigmoid(y_pred[..., :2]) + cell_grid
        
        ### adjust w and h
        pred_box_wh = tf.exp(y_pred[..., 2:4]) * np.reshape(self.anchor, [1,1,1,self.box_per_cell,2])

        ### adjust confidence
        pred_box_conf = tf.sigmoid(y_pred[..., 4])

        ### adjust class probabilities
        pred_box_class = y_pred[..., 5:]

        """
        Adjust ground truth
        """
        ### adjust x and y
        true_box_xy = y_true[..., 0:2] # relative position to the containing cell

        ### adjust w and h
        true_box_wh = y_true[..., 2:4] # number of cells accross, horizontally and vertically

        ### adjust confidence
        true_wh_half = true_box_wh / 2.
        true_mins    = true_box_xy - true_wh_half
        true_maxes   = true_box_xy + true_wh_half

        pred_wh_half = pred_box_wh / 2.
        pred_mins    = pred_box_xy - pred_wh_half
        pred_maxes   = pred_box_xy + pred_wh_half

        intersect_mins  = tf.maximum(pred_mins,  true_mins)
        intersect_maxes = tf.minimum(pred_maxes, true_maxes)
        intersect_wh    = tf.maximum(intersect_maxes - intersect_mins, 0.)
        intersect_areas = intersect_wh[..., 0] * intersect_wh[..., 1]

        true_areas = true_box_wh[..., 0] * true_box_wh[..., 1]
        pred_areas = pred_box_wh[..., 0] * pred_box_wh[..., 1]

        union_areas = pred_areas + true_areas - intersect_areas
        iou_scores  = tf.truediv(intersect_areas, union_areas)

        true_box_conf = iou_scores * y_true[..., 4]

        ### adjust class probabilities
        true_box_class = tf.argmax(y_true[..., 5:], -1)

        """
        Determine the masks
        """
        ### coordinate mask: simply the position of the ground truth boxes (the predictors)
        coord_mask = tf.expand_dims(y_true[..., 4], axis=-1) * self.coordinate_scale

        ### confidence mask: penelize predictors + penalize boxes with low IOU
        # penalize the confidence of the boxes, which have IOU with some ground truth box < 0.6
        true_xy = self.true_boxes[..., 0:2]
        true_wh = self.true_boxes[..., 2:4]#shape=(1, 1, 1, max_box_per_image , 4)

        true_wh_half = true_wh / 2.
        true_mins    = true_xy - true_wh_half
        true_maxes   = true_xy + true_wh_half

        pred_xy = tf.expand_dims(pred_box_xy, 4)
        pred_wh = tf.expand_dims(pred_box_wh, 4)

        pred_wh_half = pred_wh / 2.
        pred_mins    = pred_xy - pred_wh_half
        pred_maxes   = pred_xy + pred_wh_half

        intersect_mins  = tf.maximum(pred_mins,  true_mins)
        intersect_maxes = tf.minimum(pred_maxes, true_maxes)
        intersect_wh    = tf.maximum(intersect_maxes - intersect_mins, 0.)
        intersect_areas = intersect_wh[..., 0] * intersect_wh[..., 1]

        true_areas = true_wh[..., 0] * true_wh[..., 1]
        pred_areas = pred_wh[..., 0] * pred_wh[..., 1]

        union_areas = pred_areas + true_areas - intersect_areas
        iou_scores  = tf.truediv(intersect_areas, union_areas)

        best_ious = tf.reduce_max(iou_scores, axis=4)
        conf_mask_neg = tf.to_float(best_ious < 0.6) * (1 - y_true[..., 4]) * self.noobject_scale

        # penalize the confidence of the boxes, which are reponsible for corresponding ground truth box
        conf_mask_pos = y_true[..., 4] * self.object_scale

        ### class mask: simply the position of the ground truth boxes (the predictors)
        class_mask = y_true[..., 4] * tf.gather(self.class_wt, true_box_class) * self.class_scale

        """
        Warm-up training
        """
        no_boxes_mask = tf.to_float(coord_mask < self.coordinate_scale/2.)
        seen = tf.assign_add(seen, 1.)

        true_box_xy, true_box_wh, coord_mask = tf.cond(tf.less(seen, 1),
                              lambda: [true_box_xy + (0.5 + cell_grid) * no_boxes_mask,
                                       true_box_wh + tf.ones_like(true_box_wh) * \
                                       np.reshape(self.anchor, [1,1,1,self.box_per_cell,2]) * \
                                       no_boxes_mask,
                                       tf.ones_like(coord_mask)],
                              lambda: [true_box_xy,
                                       true_box_wh,
                                       coord_mask])

        """
        Finalize the loss
        """
        nb_coord_box = tf.reduce_sum(tf.to_float(coord_mask > 0.0))
        nb_conf_box_neg = tf.reduce_sum(tf.to_float(conf_mask_neg > 0.0))
        nb_conf_box_pos = tf.reduce_sum(tf.to_float(conf_mask_pos > 0.0))
        nb_class_box = tf.reduce_sum(tf.to_float(class_mask > 0.0))

        true_box_wh = tf.sqrt(true_box_wh)
        pred_box_wh = tf.sqrt(pred_box_wh)
        loss_xy    = tf.reduce_sum(tf.square(true_box_xy - pred_box_xy) * coord_mask) / (nb_coord_box + 1e-6) / 2.
        loss_wh    = tf.reduce_sum(tf.square(true_box_wh - pred_box_wh) * coord_mask) / (nb_coord_box + 1e-6) / 2.
        loss_conf_neg = tf.reduce_sum(tf.square(true_box_conf-pred_box_conf) * conf_mask_neg) / (nb_conf_box_neg + 1e-6) / 2.
        loss_conf_pos = tf.reduce_sum(tf.square(true_box_conf-pred_box_conf) * conf_mask_pos) / (nb_conf_box_pos + 1e-6) / 2.
        loss_conf = loss_conf_neg + loss_conf_pos
        loss_class = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=true_box_class, logits=pred_box_class)
        loss_class = tf.reduce_sum(loss_class * class_mask) / (nb_class_box + 1e-6)

        loss = tf.cond(tf.less(seen, 1),
                      lambda: loss_xy + loss_wh + loss_conf + loss_class + 10,
                      lambda: loss_xy + loss_wh + loss_conf + loss_class)

        if self.debug:
            nb_true_box = tf.reduce_sum(y_true[..., 4])
            nb_pred_box = tf.reduce_sum(tf.to_float(true_box_conf > 0.5) * tf.to_float(pred_box_conf > 0.3))

            current_recall = nb_pred_box/(nb_true_box + 1e-6)
            total_recall = tf.assign_add(total_recall, current_recall)

            loss = tf.Print(loss, [loss_xy], message='Loss XY \t', summarize=1000)
            loss = tf.Print(loss, [loss_wh], message='Loss WH \t', summarize=1000)
            loss = tf.Print(loss, [loss_conf], message='Loss Conf \t', summarize=1000)
            loss = tf.Print(loss, [loss_class], message='Loss Class \t', summarize=1000)
            loss = tf.Print(loss, [loss], message='Total Loss \t', summarize=1000)
            loss = tf.Print(loss, [current_recall], message='Current Recall \t', summarize=1000)
            loss = tf.Print(loss, [total_recall/seen], message='Average Recall \t', summarize=1000)

        return loss

**Comment by Ajaz-Ahmad** [comment]
Hi,

I made a mistake in normalizing image before assigning it to batch. However, when I feed it to the network then loss calculation sometimes work [batch size=1] for the same image and sometimes gives NAN for width and confidence values.
Any suggestions?

**Comment by Ajaz-Ahmad** [comment]
> ![Trainingshot](https://user-images.githubusercontent.com/29792736/62419453-76625f80-b678-11e9-83a8-d494f26a5f82.png)
> Hi,
> I am using your code partially and implemented pure tensorflow Tiny Yolo. I have checked the data preparation method and center calculations, box co-ordinates for resized images are same for my program as well. However, it differs in feature extraction network which I have given below:
> def build_networks(self, inputs):
> net = self.conv_layer(inputs, [3, 3, 3, 32], name = '0_conv')
> net = self.pooling_layer(net, name = '1_pool')
> 
> ```
>     net = self.conv_layer(net, [3, 3, 32, 64], name = '2_conv')
>     net = self.pooling_layer(net, name = '3_pool')
> 
>     net = self.conv_layer(net, [3, 3, 64, 128], name = '4_conv')
>     net = self.conv_layer(net, [1, 1, 128, 64], name = '5_conv')
>     net = self.conv_layer(net, [3, 3, 64, 128], name = '6_conv')
>     net = self.pooling_layer(net, name = '7_pool')
> 
>     net = self.conv_layer(net, [3, 3, 128, 256], name = '8_conv')
>     net = self.conv_layer(net, [1, 1, 256, 128], name = '9_conv')
>     net = self.conv_layer(net, [3, 3, 128, 256], name = '10_conv')
>     net = self.pooling_layer(net, name = '11_pool')
> 
>     net = self.conv_layer(net, [3, 3, 256, 512], name = '12_conv')
>     net = self.conv_layer(net, [1, 1, 512, 256], name = '13_conv')
>     net = self.conv_layer(net, [3, 3, 256, 512], name = '14_conv')
>     net = self.conv_layer(net, [1, 1, 512, 256], name = '15_conv')
>     net16 = self.conv_layer(net, [3, 3, 256, 512], name = '16_conv')
>     net = self.pooling_layer(net16, name = '17_pool')
> 
>     net = self.conv_layer(net, [3, 3, 512, 1024], name = '18_conv')
>     net = self.conv_layer(net, [1, 1, 1024, 512], name = '19_conv')
>     net = self.conv_layer(net, [3, 3, 512, 1024], name = '20_conv')
>     net = self.conv_layer(net, [1, 1, 1024, 512], name = '21_conv')
>     net = self.conv_layer(net, [3, 3, 512, 1024], name = '22_conv')
> 
>     net = self.conv_layer(net, [3, 3, 1024, 1024], name = '23_conv')
>     net24 = self.conv_layer(net, [3, 3, 1024, 1024], name = '24_conv')
> 
>     net = self.conv_layer(net16, [1, 1, 512, 64], name = '26_conv')
>     net = self.reorg(net)
> 
>     net = tf.concat([net, net24], 3)
> 
>     net = self.conv_layer(net, [3, 3, int(net.get_shape()[3]), 1024], name = '29_conv')
>     net = self.conv_layer(net, [1, 1, 1024, self.box_per_cell * (self.num_class + 5)], batch_norm=False, name = '30_conv')
> 
>     return net
> ```
> 
> The loss layer is inspired by your method of calculations but it seems I have made some mistake that the calculations come as NAN. Below is my loss layer function and max_box_per_image is 10.
> Can you help me here?
> Another questions is where do you normalize to bbox co-ordinates, if you do that?
> If you need more info please let me know I will add files to my repository.
> Your help is appreciated.
> Thanks.
> 
> def loss_layer(self,y_true,y_pred):#, y_true=shape=(1, 1, 1, max_box_per_image , 4)
> #13,13,5,8....................1,1,1,10,4-ytrue
> #?,13,13,5,8
> #4,
> print('ytrue',y_true)
> y_pred=tf.reshape(y_pred,[self.batch_size,self.cell_size,self.cell_size,self.box_per_cell,5+self.num_class])
> print('ypred',y_pred)
> mask_shape = tf.shape(y_true)[:4]
> print(mask_shape)
> #1,13,13,1,1
> cell_x = tf.to_float(tf.reshape(tf.tile(tf.range(self.cell_size), [self.cell_size]), (1, self.cell_size, self.cell_size, 1, 1)))
> print(cell_x)
> #1,13,13,1,1
> cell_y = tf.to_float(tf.reshape(tf.tile(tf.range(self.cell_size), [self.cell_size]), (1, self.cell_size, self.cell_size, 1, 1)))
> print(cell_y)
> cell_y = tf.transpose(cell_y, (0,2,1,3,4))
> print(cell_y)
> #1,13,13,5,2
> cell_grid = tf.tile(tf.concat([cell_x,cell_y], -1), [self.batch_size, 1, 1, self.box_per_cell, 1])
> print(cell_grid)
> #?,13,13,5
> coord_mask = tf.zeros(mask_shape)
> #?,13,13,5
> class_mask = tf.zeros(mask_shape)
> 
> ```
>     seen = tf.Variable(0.)
>     total_recall = tf.Variable(0.)
> 
>     """
>     Adjust prediction
>     """
>     ### adjust x and y
>     print('y_pred[...,:2]',y_pred[...,:2])
>     print('cell_grid',cell_grid)
>     pred_box_xy = tf.sigmoid(y_pred[..., :2]) + cell_grid
>     
>     ### adjust w and h
>     pred_box_wh = tf.exp(y_pred[..., 2:4]) * np.reshape(self.anchor, [1,1,1,self.box_per_cell,2])
> 
>     ### adjust confidence
>     pred_box_conf = tf.sigmoid(y_pred[..., 4])
> 
>     ### adjust class probabilities
>     pred_box_class = y_pred[..., 5:]
> 
>     """
>     Adjust ground truth
>     """
>     ### adjust x and y
>     true_box_xy = y_true[..., 0:2] # relative position to the containing cell
> 
>     ### adjust w and h
>     true_box_wh = y_true[..., 2:4] # number of cells accross, horizontally and vertically
> 
>     ### adjust confidence
>     true_wh_half = true_box_wh / 2.
>     true_mins    = true_box_xy - true_wh_half
>     true_maxes   = true_box_xy + true_wh_half
> 
>     pred_wh_half = pred_box_wh / 2.
>     pred_mins    = pred_box_xy - pred_wh_half
>     pred_maxes   = pred_box_xy + pred_wh_half
> 
>     intersect_mins  = tf.maximum(pred_mins,  true_mins)
>     intersect_maxes = tf.minimum(pred_maxes, true_maxes)
>     intersect_wh    = tf.maximum(intersect_maxes - intersect_mins, 0.)
>     intersect_areas = intersect_wh[..., 0] * intersect_wh[..., 1]
> 
>     true_areas = true_box_wh[..., 0] * true_box_wh[..., 1]
>     pred_areas = pred_box_wh[..., 0] * pred_box_wh[..., 1]
> 
>     union_areas = pred_areas + true_areas - intersect_areas
>     iou_scores  = tf.truediv(intersect_areas, union_areas)
> 
>     true_box_conf = iou_scores * y_true[..., 4]
> 
>     ### adjust class probabilities
>     true_box_class = tf.argmax(y_true[..., 5:], -1)
> 
>     """
>     Determine the masks
>     """
>     ### coordinate mask: simply the position of the ground truth boxes (the predictors)
>     coord_mask = tf.expand_dims(y_true[..., 4], axis=-1) * self.coordinate_scale
> 
>     ### confidence mask: penelize predictors + penalize boxes with low IOU
>     # penalize the confidence of the boxes, which have IOU with some ground truth box < 0.6
>     true_xy = self.true_boxes[..., 0:2]
>     true_wh = self.true_boxes[..., 2:4]#shape=(1, 1, 1, max_box_per_image , 4)
> 
>     true_wh_half = true_wh / 2.
>     true_mins    = true_xy - true_wh_half
>     true_maxes   = true_xy + true_wh_half
> 
>     pred_xy = tf.expand_dims(pred_box_xy, 4)
>     pred_wh = tf.expand_dims(pred_box_wh, 4)
> 
>     pred_wh_half = pred_wh / 2.
>     pred_mins    = pred_xy - pred_wh_half
>     pred_maxes   = pred_xy + pred_wh_half
> 
>     intersect_mins  = tf.maximum(pred_mins,  true_mins)
>     intersect_maxes = tf.minimum(pred_maxes, true_maxes)
>     intersect_wh    = tf.maximum(intersect_maxes - intersect_mins, 0.)
>     intersect_areas = intersect_wh[..., 0] * intersect_wh[..., 1]
> 
>     true_areas = true_wh[..., 0] * true_wh[..., 1]
>     pred_areas = pred_wh[..., 0] * pred_wh[..., 1]
> 
>     union_areas = pred_areas + true_areas - intersect_areas
>     iou_scores  = tf.truediv(intersect_areas, union_areas)
> 
>     best_ious = tf.reduce_max(iou_scores, axis=4)
>     conf_mask_neg = tf.to_float(best_ious < 0.6) * (1 - y_true[..., 4]) * self.noobject_scale
> 
>     # penalize the confidence of the boxes, which are reponsible for corresponding ground truth box
>     conf_mask_pos = y_true[..., 4] * self.object_scale
> 
>     ### class mask: simply the position of the ground truth boxes (the predictors)
>     class_mask = y_true[..., 4] * tf.gather(self.class_wt, true_box_class) * self.class_scale
> 
>     """
>     Warm-up training
>     """
>     no_boxes_mask = tf.to_float(coord_mask < self.coordinate_scale/2.)
>     seen = tf.assign_add(seen, 1.)
> 
>     true_box_xy, true_box_wh, coord_mask = tf.cond(tf.less(seen, 1),
>                           lambda: [true_box_xy + (0.5 + cell_grid) * no_boxes_mask,
>                                    true_box_wh + tf.ones_like(true_box_wh) * \
>                                    np.reshape(self.anchor, [1,1,1,self.box_per_cell,2]) * \
>                                    no_boxes_mask,
>                                    tf.ones_like(coord_mask)],
>                           lambda: [true_box_xy,
>                                    true_box_wh,
>                                    coord_mask])
> 
>     """
>     Finalize the loss
>     """
>     nb_coord_box = tf.reduce_sum(tf.to_float(coord_mask > 0.0))
>     nb_conf_box_neg = tf.reduce_sum(tf.to_float(conf_mask_neg > 0.0))
>     nb_conf_box_pos = tf.reduce_sum(tf.to_float(conf_mask_pos > 0.0))
>     nb_class_box = tf.reduce_sum(tf.to_float(class_mask > 0.0))
> 
>     true_box_wh = tf.sqrt(true_box_wh)
>     pred_box_wh = tf.sqrt(pred_box_wh)
>     loss_xy    = tf.reduce_sum(tf.square(true_box_xy - pred_box_xy) * coord_mask) / (nb_coord_box + 1e-6) / 2.
>     loss_wh    = tf.reduce_sum(tf.square(true_box_wh - pred_box_wh) * coord_mask) / (nb_coord_box + 1e-6) / 2.
>     loss_conf_neg = tf.reduce_sum(tf.square(true_box_conf-pred_box_conf) * conf_mask_neg) / (nb_conf_box_neg + 1e-6) / 2.
>     loss_conf_pos = tf.reduce_sum(tf.square(true_box_conf-pred_box_conf) * conf_mask_pos) / (nb_conf_box_pos + 1e-6) / 2.
>     loss_conf = loss_conf_neg + loss_conf_pos
>     loss_class = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=true_box_class, logits=pred_box_class)
>     loss_class = tf.reduce_sum(loss_class * class_mask) / (nb_class_box + 1e-6)
> 
>     loss = tf.cond(tf.less(seen, 1),
>                   lambda: loss_xy + loss_wh + loss_conf + loss_class + 10,
>                   lambda: loss_xy + loss_wh + loss_conf + loss_class)
> 
>     if self.debug:
>         nb_true_box = tf.reduce_sum(y_true[..., 4])
>         nb_pred_box = tf.reduce_sum(tf.to_float(true_box_conf > 0.5) * tf.to_float(pred_box_conf > 0.3))
> 
>         current_recall = nb_pred_box/(nb_true_box + 1e-6)
>         total_recall = tf.assign_add(total_recall, current_recall)
> 
>         loss = tf.Print(loss, [loss_xy], message='Loss XY \t', summarize=1000)
>         loss = tf.Print(loss, [loss_wh], message='Loss WH \t', summarize=1000)
>         loss = tf.Print(loss, [loss_conf], message='Loss Conf \t', summarize=1000)
>         loss = tf.Print(loss, [loss_class], message='Loss Class \t', summarize=1000)
>         loss = tf.Print(loss, [loss], message='Total Loss \t', summarize=1000)
>         loss = tf.Print(loss, [current_recall], message='Current Recall \t', summarize=1000)
>         loss = tf.Print(loss, [total_recall/seen], message='Average Recall \t', summarize=1000)
> 
>     return loss
> ```
